- name: "Create user"
  user:
    name: redteam
    comment: "super redteam"
    uid: 1040
    group: sudo

- name: "Create SSH key"
  user:
    name: redteam
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
 
- name: "Change ssh port"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port 2224"
  notify: restart-ssh

- name: "Change inventory ansible ssh port"
  set_fact:
    ansible_ssh_port: "2242"

- name: change ssh port in inventory
  lineinfile:
    dest: inventory_file
    insert_after: '[all:vars]'
    line: 'ansible_ssh_port=2242'
    
- name: "Create log directory"
  file:
    path: /var/log/beats
    state: directory
    owner: redteam
    mode: 0755
    recurse: yes
