version: '2'

networks:
  dionaea_local:

services:
  dionaea:
    container_name: dionaea
    stdin_open: true
    restart: always
    networks:
     - dionaea_local
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "20:20"
     - "21:21"
     - "42:42"
     - "69:69/udp"
     - "81:80"
     - "135:135"
     - "444:443"
     - "445:445"
     - "1433:1433"
     - "1723:1723"
     - "1886:1883"
     - "3306:3306"
     - "5060:5060"
     - "5060:5060/udp"
     - "5061:5061"
     - "27017:27017"
    image: "toto"
    volumes:
     - /data/dionaea/log:/opt/dionaea/var/log


