#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  enabled: false
  paths:
    - /var/log/beats/ssh.log
  fields:
    indextype: "ssh"

- type: log
  enabled: false
  paths:
    - /var/log/opencanary/opencanary.log
  fields:
    indextype: "opencanary"

- type: log
  enabled: true
  paths:
    - /var/lib/docker/volumes/cowrie_cowrie-log/_data/cowrie.json
  fields:
    indextype: "cowrie"

- type: log
  enabled: true
  paths:
    - /var/log/dionaea.log
  fields:
    indextype: "dionaea"

- type: log
  enabled: true
  paths:
    - /var/log/iptables.log
  fields:
    indextype: "iptables"

- type: log
  enabled: true
  paths:
    - /var/log/arpalert.log
  fields:
    indextype: "arpalert"

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3

#----------------------------- Logstash output --------------------------------

output.logstash:
  hosts: ["51.38.179.48:5044"]
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
#ssl.key: "/etc/pki/client/cert.key"
