- name: "Copy configuration files"
  copy:
    src: /opt/HoneyPy/config/files
    dest: /opt/

- name: "Copy handlers"
  copy:
    src: /opt/HoneyPy/handlers
    dest: /opt

- name: "Overwrite filebeat configuration file"
  shell: cat /opt/files/filebeat.yml > /etc/filebeat/filebeat.yml
  notify:
     - restart-filebeat
