---
- name: "Configure OS"
  hosts: slaves
  remote_user: root
  roles:
  - system
  
- name: "Install dependencies"
  hosts: slaves
  remote_user: root
  roles:
  - install
  - setup

- name: "Run dockers"
  hosts: slaves
  remote_user: redteam
  roles:
  - dockerize
