#- name: "Clean all docker images / instances"
#  command: "{{ item }}"
#  with_items:
#    - docker kill $(docker ps -q)
#    - docker rm $(docker ps -a -q)
#    - docker rmi $(docker images -q)

#- name: "Launch ssh instance"
#  command: "{{ item }}"
#  with_items:
#    - docker build -t honeysshimg /opt/handlers/ssh/
#    - docker run -d --rm --name honeySSH -p 22:2242 -v /var/log/beat:/var/ honeysshimg

- name: "Upload handlers"
  synchronize: src=/opt/HoneyPy/handlers dest=/opt
  register: sync_res

- name: "Build image"
  docker_image: >
    name=holyssh
    tag=v1
    path=/opt/
    state=present
  when: sync_res.changed

- name: "Run container"
  docker:
    name: holysshinstance
    image: "holyssh:v1"
    state: reloaded
    pull: always
    devices:
    - "/var/log/beat:/var/:rwm"
    ports:
    - "22:2242"
    env:
      SECRET_KEY: ssssssssssss
