
#- name: "stop all docker containers"
#  shell: docker stop $(docker ps -a -q)
#  ignore_errors: true

#- name: "remove all docker containers"
#  shell: docker rm $(docker ps -a -q)
#  ignore_errors: true

#- name: "remove all docker images"
#  shell: docker rmi holyyssh opencanary
#  ignore_errors: true

- name: "Some tools for python docker API"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
  - { name: docker-compose, version: 1.22.0 }

- name: "Build ssh"
  docker_image:
    name: holyssh
    path: /opt/handlers/ssh/
    state: build

- name: "build opencanary"
  docker_image:
    name: opencanary
    path: /opt/handlers/openCanary/
    state: build

- name: "Ensure ssh is running"
  docker_container:
    image: holyssh
    name: holysshinst2
    state: started
    restart_policy: always
    ports:
    - 22:2242
    volumes:
    - /var/log/beats:/var

- name: "Ensure opencanary is running"
  docker_container:
    image: opencanary:latest
    name: opencanaryinst
    state: started
    restart_policy: always
    ports:
    - 3306:3306
    - 80:80
    - 21:21
    volumes:
    - /var/log/opencanary/:/var/log/opencanary/
