- name: "stop all docker containers"
  shell: docker stop $(docker ps -a -q)
  ignore_errors: true

- name: "remove all docker containers"
  shell: docker rm $(docker ps -a -q)
  ignore_errors: true

- name: "remove all docker images"
  shell: docker rmi holyyssh opencanary
  ignore_errors: true

#- name: "Build images"
#  docker_image:
#    name: holyssh
#    path: /opt/handlers/ssh/
#    state: build

#- name: Ensure the test container is running.
#  docker_container:
#    image: holyssh:latest
#    name: holysshinst
#    state: started
#    restart_policy: always
#    ports:
#    - 22:2242
#    devices:
#    - "/var/log/beats:/var/:rwm"

- name: "build ssh"
  shell: docker build -t holyssh /opt/handlers/ssh/

- name: "run ssh "
  shell: docker run -d --rm --name holysshinst -p 22:2242 -v /var/log/beats:/var/ holyssh

- name: "build openc"
  shell: docker build -t opencanary /opt/handlers/openCanary/

- name: "run openc"
  shell: docker run -d  -v /var/log/opencanary/:/var/log/opencanary/ -p 3306:3306 -p 80:80 --name opencanaryinst opencanary
