- name: "restart-ssh"
  service: name=ssh state=restarted
  notify: status-ssh
  
- name: "status-ssh"
  service: name=ssh state=started enabled=yes

- name: "restart-filebeat"
  service: name=filebeat state=restarted
  notify: status-filebeat

-name: "status-filebeat"
  service: name=filebeat state=started enabled=yes
